[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_rounds = 200

fs_permissions = [{ access = "read", path = "./broadcast" }, { access = "read", path = "./reports" }, { access = "read-write", path = "./script/target" }]
gas_reports = ["MerkleAirdrop"]
